---
header-includes: |
  \usepackage{fancyhdr}
  \pagestyle{fancy}
  \fancyhead[LO,L]{\textbf{MTH-361 A} | Spring 2025}
  \fancyhead[RO,R]{\textbf{W 2/19 Worksheet} | Pg. \thepage}
  \fancyfoot[CO,C]{}
  \usepackage{float}
  \usepackage{multirow}
output:
  bookdown::pdf_document2:
    toc: no
    number_section: no
urlcolor: blue
link-citations: yes
bibliography: ../../../references.bib
csl: ../../../mbe.csl
nocite: '@*'
geometry: "left=0.50in,right=0.50in,top=0.75in,bottom=0.75in"
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

**Name:**

**Collaborators:**

\noindent\rule{\textwidth}{1pt}
**Instructions:** 

> You must submit your worksheet individually by end-of-class or end-of-day. Your name must exist in your worksheet and the names of your collaborators.

Worksheets are marked mostly on completion, and partially on correctness. It will be marked either pass or fail, there will no detailed feedback on worksheets, and no opportunities for revisions and make-up.
\noindent\rule{\textwidth}{1pt}

## Distinguish Between Geometric or Exponential R.V.

### 1. Engine Failure

A commercial airline pilot monitors engine performance during long-haul flights. The probability that a given engine fails during a flight is $0.001$. Let $X$ be the number of flights the pilot completes until the first engine failure occurs.

a. What type of r.v. is $X$? Explain your reasoning.
\vfill

b. Interpret the probability of engine failure. Explain your reasoning.
\vfill

\newpage

### 2. Cafe Processing Times

Suppose you walk into a coffee shop and see that an order was just completed after $3$ minutes of processing. Let $X$ denote the time (in minutes from when the order was placed) that the order was completed.

a. What type of r.v. is $X$? Explain your reasoning.
\vfill

b. What is its rate? Explain your reasoning.
\vfill

c. Interpret the rate in context. Explain your reasoning.
\vfill

## **References**

::: {#refs}
:::
