---
header-includes: |
  \usepackage{fancyhdr}
  \pagestyle{fancy}
  \fancyhead[LO,L]{\textbf{MTH-361 A} | Spring 2025}
  \fancyhead[RO,R]{\textbf{F 2/7 Worksheet} | Pg. \thepage}
  \fancyfoot[CO,C]{}
  \usepackage{float}
  \usepackage{multirow}
output:
  bookdown::pdf_document2:
    toc: no
    number_section: no
urlcolor: blue
link-citations: yes
bibliography: ../../../references.bib
csl: ../../../mbe.csl
nocite: '@*'
geometry: "left=0.50in,right=0.50in,top=0.75in,bottom=0.75in"
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

**Name:** \textcolor{blue}{Solutions}

**Collaborators:**

\noindent\rule{\textwidth}{1pt}
**Instructions:** 

> You must submit your worksheet individually by end-of-class or end-of-day. Your name must exist in your worksheet and the names of your collaborators.

Worksheets are marked mostly on completion, and partially on correctness. It will be marked either pass or fail, there will no detailed feedback on worksheets, and no opportunities for revisions and make-up.
\noindent\rule{\textwidth}{1pt}

## Proving the Variance Formula

### 1. Derive the Variance Formula Using Expectation Properties

Use the expected value properties to show that $$\displaystyle \text{Var}(X) = \text{E}\left((X - \text{E}(X))^2\right) = \text{E}\left(X^2 \right) - \left( \text{E}(X) \right)^2.$$ Show each step and what properties used.

\textcolor{blue}{
\[
\begin{aligned}
\text{Var}(X) & = \text{E}\left((X - \text{E}(X))^2\right) \\
              & = \text{E}\left( X^2 - 2X\text{E}(X) + \left(\text{E}(X)\right)^2 \right) \longrightarrow \text{expand the quadratic} \\
              & = \text{E}\left( X^2 \right) - \text{E}(2X\text{E}(X)) + \text{E}\left(\left(\text{E}(X)\right)^2\right) \longrightarrow \text{apply the linearity property} \\
              & = \text{E}\left( X^2 \right) - 2\text{E}(X)\text{E}(X) + \left(\text{E}(X)\right)^2 \longrightarrow \text{apply the constant property} \\
              & = \text{E}\left( X^2 \right) - 2\left(\text{E}(X)\right)^2 + \left(\text{E}(X)\right)^2 \longrightarrow \text{simplify terms} \\
\text{Var}(X) & = \text{E}\left( X^2 \right) - \left(\text{E}(X)\right)^2
\end{aligned}
\]
The expected value is a constant and variance is the squared average distance from the expectation.
}
\vfill

## **References**

::: {#refs}
:::
